### ISSUE TITLE
Feature request: top navbar that does not collapse on desktops

### ISSUE THREAD

**Issue by Rudd-O** [collective/plonetheme.future_imperfect#1]
The top bar of the theme, which contains the search box and the site sections (top level navigatable items) currently (as of 1.0a) collapses into a menu, which means the tabs do not show unless the user clicks on the menu.  This is problematic.

If I could request that there be a knob to turn the menu into a traditional tab (section) bar when the browser is wide enough (say, on a desktop), and have the menu collapse as it does on phones and other small screens, that would be 100% phenomenal.  This may require the elimination of the "Type title here" text, of course.

What would it take to get this feature on the theme?

Thank you in advance. :-)

**Comment by vikas-parashar** [comment]
That behaviour is by design so I am not going to change it. If you want traditional menu you can fork and tweak the theme according to your need.
